SELECT DISTINCT INTO $OUTDEV
	EA.ALIAS
	, E_LOC_NURSE_UNIT_DISP = UAR_GET_CODE_DISPLAY(E.LOC_NURSE_UNIT_CD)
	, E_LOC_ROOM_DISP = UAR_GET_CODE_DISPLAY(E.LOC_ROOM_CD)
	, PR.NAME_FULL_FORMATTED
	, O.ORDER_MNEMONIC
	, O.CLINICAL_DISPLAY_LINE
	, O.ACTIVE_STATUS_DT_TM
	, U_CATALOG_DISP = UAR_GET_CODE_DISPLAY(U.CATALOG_CD)
	, U_ORDER_STATUS_DISP = UAR_GET_CODE_DISPLAY(U.ORDER_STATUS_CD)
	, M_ORGANISM_DISP = UAR_GET_CODE_DESCRIPTION(M.ORGANISM_CD)

FROM
	ENCOUNTER   E
	, ORDERS   O
	, PHA_PROD_DISP_OBS_ST   P
	, PRSNL   PR
	, ENCNTR_ALIAS   EA
	, UM_CHARGE_EVENT_ST   U
	, MIC_TASK_LOG   M
	, ORDERS   ORD

PLAN E WHERE E.LOC_FACILITY_CD = 38992032.00
	AND E.DISCH_DT_TM = NULL
JOIN O WHERE O.ENCNTR_ID = E.ENCNTR_ID
	AND O.ORDER_STATUS_CD = 2550.00
	AND O.CATALOG_TYPE_CD = 2516.00
	AND O.ORDER_MNEMONIC NOT LIKE "*cadexomer*"
	AND O.ORDER_MNEMONIC NOT LIKE "*iodosorb*"
	OR O.ORDER_MNEMONIC LIKE "*dazole*"

JOIN P WHERE P.ORDER_ID = O.ORDER_ID
	AND (P.ROOT_THERAP_CLASS = "anti-infectives"
	OR P.PARENT_THERAP_CLASS = "anti-infectives"
	OR P.THERAP_CLASS LIKE "*anti-infect*")
JOIN EA WHERE EA.ENCNTR_ID = E.ENCNTR_ID
	AND EA.ENCNTR_ALIAS_TYPE_CD = 1077
JOIN PR WHERE PR.PERSON_ID = O.ACTIVE_STATUS_PRSNL_ID
	AND PR.PHYSICIAN_IND = 1
JOIN U WHERE U.ENCNTR_ID = E.ENCNTR_ID
    AND U.ACCESSION_FORMAT_CD = 4152159.00
JOIN M WHERE M.ORDER_ID = U.ORDER_ID
	AND M.ORGANISM_CD NOT IN (6050767.00, 673908.00, 673907.00)
JOIN ORD WHERE ORD.ENCNTR_ID = E.ENCNTR_ID
	AND ORD.ORDER_MNEMONIC = O.ORDER_MNEMONIC
	AND ORD.ORIG_ORDER_DT_TM <= CNVTLOOKBEHIND("2,D")

GROUP BY
	EA.ALIAS
	, E.LOC_NURSE_UNIT_CD
	, E.LOC_ROOM_CD
	, PR.NAME_FULL_FORMATTED
	, O.ORDER_MNEMONIC
	, O.CLINICAL_DISPLAY_LINE
	, O.ACTIVE_STATUS_DT_TM
	, U.CATALOG_CD
	, U.ORDER_STATUS_CD
	, M.ORGANISM_CD

ORDER BY
	EA.ALIAS
